server:
  port: 8080

spring:
  profiles:   ## application-{}.yml
    active: $spring.profiles.active$

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.dialect.storage_engine: innodb
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy