spring:
  application:
    name: shop_config
  cloud:
    config:
      server:
        git:
          ## prefix
          uri: https://github.com/baihezhuo/learngit
          search-paths:  #相对路径 #user-service, hello-service, luck-service


server:
  port: 4000

