#spring:
#  application:
#    name: shop_eureka
##security:
##  basic:
##    enabled: true
##  user:
##    name: jacky
##    password: admin
#---
#server:
#  port: 8761
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: peer1        #Eureka实例的主机名
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/  #Eureka节点相互注册
##      default-zone: http://eureka2:8762/eureka/
#      register-with-eureka: true
#---
#server:
#  port: 8762
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2      #Eureka实例的主机名
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
#      register-with-eureka: true
#---
#server:
#  port: 8763
#spring:
#  profiles: peer3
#eureka:
#  instance:
#    hostname: peer3    #Eureka实例的主机名
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#      register-with-eureka: true
